version: '3.9'
services:
  backend:
    build: .
    working_dir: /app/api
    volumes:
      - ./vector_store:/app/api/vector_store
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build: .
    working_dir: /app/ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
